namespace TheMurderStoneArchive.Helpers
{
    /// <summary>
    /// Global region keyword and centroid reference data.
    /// Used for inferring a named geographic region from a location string or coordinate.
    ///
    /// Keywords are matched as whole words (not arbitrary substrings) so that, for example,
    /// "kent" does not match "Kentucky" and "victoria" does not match "Victorian".
    ///
    /// Where a location name contains no recognisable keyword, the centroid table is used
    /// for a proximity-based fallback: the nearest centroid within a caller-defined radius
    /// is returned.
    ///
    /// Coverage: British Isles • Western Europe • Northern/Eastern/Southern Europe
    ///           Middle East & North Africa • Sub-Saharan Africa • South Asia
    ///           East & Southeast Asia • Americas • Oceania
    /// </summary>
    public static class RegionData
    {
        // ── Keyword → canonical region name ─────────────────────────────────────
        // Keys are matched as whole words (case-insensitive).
        // Order entries from most-specific to least-specific within each group so
        // that longer compound names (e.g. "nottinghamshire") are tested before
        // any shorter component that happens to appear in them.
        public static readonly IReadOnlyDictionary<string, string> Keywords =
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                // ── England: full county / historic region names ─────────────────
                ["nottinghamshire"]  = "Nottinghamshire",
                ["northamptonshire"] = "Northamptonshire",
                ["buckinghamshire"]  = "Buckinghamshire",
                ["cambridgeshire"]   = "Cambridgeshire",
                ["northumberland"]   = "Northumberland",
                ["gloucestershire"]  = "Gloucestershire",
                ["worcestershire"]   = "Worcestershire",
                ["leicestershire"]   = "Leicestershire",
                ["herefordshire"]    = "Herefordshire",
                ["staffordshire"]    = "Staffordshire",
                ["hertfordshire"]    = "Hertfordshire",
                ["bedfordshire"]     = "Bedfordshire",
                ["lincolnshire"]     = "Lincolnshire",
                ["westmorland"]      = "Westmorland",
                ["oxfordshire"]      = "Oxfordshire",
                ["huntingdonshire"]  = "Huntingdonshire",
                ["warwickshire"]     = "Warwickshire",
                ["shropshire"]       = "Shropshire",
                ["derbyshire"]       = "Derbyshire",
                ["lancashire"]       = "Lancashire",
                ["yorkshire"]        = "Yorkshire",
                ["hampshire"]        = "Hampshire",
                ["wiltshire"]        = "Wiltshire",
                ["berkshire"]        = "Berkshire",
                ["somerset"]         = "Somerset",
                ["cornwall"]         = "Cornwall",
                ["cheshire"]         = "Cheshire",
                ["cumbria"]          = "Cumbria",
                ["suffolk"]          = "Suffolk",
                ["norfolk"]          = "Norfolk",
                ["dorset"]           = "Dorset",
                ["surrey"]           = "Surrey",
                ["sussex"]           = "Sussex",
                ["essex"]            = "Essex",
                ["london"]           = "Greater London",
                ["devon"]            = "Devon",
                ["durham"]           = "County Durham",
                ["rutland"]          = "Rutland",
                ["middlesex"]        = "Middlesex",
                ["kent"]             = "Kent",

                // ── Scotland ────────────────────────────────────────────────────
                ["aberdeenshire"]    = "Aberdeenshire",
                ["stirlingshire"]    = "Stirlingshire",
                ["renfrewshire"]     = "Renfrewshire",
                ["lanarkshire"]      = "Lanarkshire",
                ["perthshire"]       = "Perthshire",
                ["caithness"]        = "Caithness",
                ["sutherland"]       = "Sutherland",
                ["ayrshire"]         = "Ayrshire",
                ["shetland"]         = "Shetland",
                ["inverness"]        = "Inverness",
                ["edinburgh"]        = "Edinburgh",
                ["aberdeen"]         = "Aberdeen",
                ["highland"]         = "Scottish Highlands",
                ["strathclyde"]      = "Strathclyde",
                ["lothian"]          = "Lothian",
                ["glasgow"]          = "Glasgow",
                ["dundee"]           = "Dundee",
                ["orkney"]           = "Orkney",
                ["argyll"]           = "Argyll",
                ["angus"]            = "Angus",
                ["moray"]            = "Moray",
                ["fife"]             = "Fife",
                ["scotland"]         = "Scotland",

                // ── Wales ───────────────────────────────────────────────────────
                ["carmarthenshire"]  = "Carmarthenshire",
                ["pembrokeshire"]    = "Pembrokeshire",
                ["denbighshire"]     = "Denbighshire",
                ["monmouthshire"]    = "Monmouthshire",
                ["flintshire"]       = "Flintshire",
                ["ceredigion"]       = "Ceredigion",
                ["glamorgan"]        = "Glamorgan",
                ["anglesey"]         = "Anglesey",
                ["wrexham"]          = "Wrexham",
                ["gwynedd"]          = "Gwynedd",
                ["powys"]            = "Powys",
                ["cardiff"]          = "Cardiff",
                ["swansea"]          = "Swansea",
                ["wales"]            = "Wales",

                // ── Ireland ─────────────────────────────────────────────────────
                ["londonderry"]      = "County Londonderry",
                ["tipperary"]        = "Tipperary",
                ["fermanagh"]        = "Fermanagh",
                ["donegal"]          = "Donegal",
                ["kilkenny"]         = "Kilkenny",
                ["wicklow"]          = "Wicklow",
                ["wexford"]          = "Wexford",
                ["connacht"]         = "Connacht",
                ["leinster"]         = "Leinster",
                ["munster"]          = "Munster",
                ["ulster"]           = "Ulster",
                ["antrim"]           = "County Antrim",
                ["armagh"]           = "County Armagh",
                ["tyrone"]           = "County Tyrone",
                ["galway"]           = "Galway",
                ["limerick"]         = "Limerick",
                ["sligo"]            = "Sligo",
                ["kerry"]            = "County Kerry",
                ["dublin"]           = "Dublin",
                ["cork"]             = "County Cork",
                ["mayo"]             = "County Mayo",
                ["ireland"]          = "Ireland",

                // ── France ──────────────────────────────────────────────────────
                ["île-de-france"]    = "Île-de-France",
                ["normandie"]        = "Normandy",
                ["normandy"]         = "Normandy",
                ["bretagne"]         = "Brittany",
                ["brittany"]         = "Brittany",
                ["bourgogne"]        = "Burgundy",
                ["burgundy"]         = "Burgundy",
                ["occitanie"]        = "Occitanie",
                ["languedoc"]        = "Languedoc",
                ["aquitaine"]        = "Aquitaine",
                ["champagne"]        = "Champagne",
                ["auvergne"]         = "Auvergne",
                ["picardie"]         = "Picardy",
                ["picardy"]          = "Picardy",
                ["lorraine"]         = "Lorraine",
                ["provence"]         = "Provence",
                ["touraine"]         = "Touraine",
                ["gascony"]          = "Gascony",
                ["alsace"]           = "Alsace",
                ["poitou"]           = "Poitou",
                ["anjou"]            = "Anjou",
                ["paris"]            = "Île-de-France",
                ["france"]           = "France",

                // ── Germany ─────────────────────────────────────────────────────
                ["württemberg"]      = "Baden-Württemberg",
                ["westphalia"]       = "Westphalia",
                ["westfalen"]        = "Westphalia",
                ["thuringia"]        = "Thuringia",
                ["thüringen"]        = "Thuringia",
                ["rhineland"]        = "Rhineland",
                ["rheinland"]        = "Rhineland",
                ["pomerania"]        = "Pomerania",
                ["prussian"]         = "Prussia",
                ["prussia"]          = "Prussia",
                ["hanover"]          = "Hanover",
                ["hannover"]         = "Hanover",
                ["bavaria"]          = "Bavaria",
                ["münchen"]          = "Bavaria",
                ["munich"]           = "Bavaria",
                ["sachsen"]          = "Saxony",
                ["saxony"]           = "Saxony",
                ["hessen"]           = "Hesse",
                ["hesse"]            = "Hesse",
                ["silesia"]          = "Silesia",
                ["swabia"]           = "Swabia",
                ["berlin"]           = "Berlin",
                ["hamburg"]          = "Hamburg",
                ["bremen"]           = "Bremen",
                ["germany"]          = "Germany",

                // ── Austria / Switzerland ────────────────────────────────────────
                ["bohemia"]          = "Bohemia",
                ["moravia"]          = "Moravia",
                ["austria"]          = "Austria",
                ["styria"]           = "Styria",
                ["tyrol"]            = "Tyrol",
                ["tirol"]            = "Tyrol",
                ["switzerland"]      = "Switzerland",

                // ── Italy ───────────────────────────────────────────────────────
                ["emilia-romagna"]   = "Emilia-Romagna",
                ["lombardia"]        = "Lombardy",
                ["lombardy"]         = "Lombardy",
                ["piemonte"]         = "Piedmont",
                ["piedmont"]         = "Piedmont",
                ["sardegna"]         = "Sardinia",
                ["sardinia"]         = "Sardinia",
                ["toscana"]          = "Tuscany",
                ["tuscany"]          = "Tuscany",
                ["sicilia"]          = "Sicily",
                ["sicily"]           = "Sicily",
                ["calabria"]         = "Calabria",
                ["campania"]         = "Campania",
                ["liguria"]          = "Liguria",
                ["umbria"]           = "Umbria",
                ["veneto"]           = "Veneto",
                ["emilia"]           = "Emilia-Romagna",
                ["puglia"]           = "Puglia",
                ["lazio"]            = "Lazio",
                ["venice"]           = "Veneto",
                ["naples"]           = "Campania",
                ["florence"]         = "Tuscany",
                ["bologna"]          = "Emilia-Romagna",
                ["genoa"]            = "Liguria",
                ["milan"]            = "Lombardy",
                ["turin"]            = "Piedmont",
                ["rome"]             = "Lazio",
                ["italy"]            = "Italy",

                // ── Spain ───────────────────────────────────────────────────────
                ["extremadura"]      = "Extremadura",
                ["cataluña"]         = "Catalonia",
                ["catalonia"]        = "Catalonia",
                ["catalunya"]        = "Catalonia",
                ["andalucía"]        = "Andalusia",
                ["andalusia"]        = "Andalusia",
                ["cantabria"]        = "Cantabria",
                ["asturias"]         = "Asturias",
                ["castilla"]         = "Castile",
                ["castile"]          = "Castile",
                ["navarra"]          = "Navarre",
                ["navarre"]          = "Navarre",
                ["aragón"]           = "Aragon",
                ["aragon"]           = "Aragon",
                ["basque"]           = "Basque Country",
                ["galicia"]          = "Galicia",
                ["valencia"]         = "Valencia",
                ["murcia"]           = "Murcia",
                ["madrid"]           = "Madrid",
                ["spain"]            = "Spain",

                // ── Portugal ────────────────────────────────────────────────────
                ["alentejo"]         = "Alentejo",
                ["algarve"]          = "Algarve",
                ["lisbon"]           = "Lisbon",
                ["douro"]            = "Douro",
                ["minho"]            = "Minho",
                ["portugal"]         = "Portugal",

                // ── Low Countries ────────────────────────────────────────────────
                ["vlaanderen"]       = "Flanders",
                ["flanders"]         = "Flanders",
                ["wallonie"]         = "Wallonia",
                ["wallonia"]         = "Wallonia",
                ["gelderland"]       = "Gelderland",
                ["overijssel"]       = "Overijssel",
                ["friesland"]        = "Friesland",
                ["zeeland"]          = "Zeeland",
                ["brabant"]          = "Brabant",
                ["holland"]          = "Holland",
                ["netherlands"]      = "Netherlands",
                ["belgium"]          = "Belgium",

                // ── Scandinavia ──────────────────────────────────────────────────
                ["trøndelag"]        = "Trøndelag",
                ["vestfold"]         = "Vestfold",
                ["jutland"]          = "Jutland",
                ["lapland"]          = "Lapland",
                ["dalarna"]          = "Dalarna",
                ["skåne"]            = "Scania",
                ["scania"]           = "Scania",
                ["norway"]           = "Norway",
                ["sweden"]           = "Sweden",
                ["denmark"]          = "Denmark",
                ["finland"]          = "Finland",
                ["iceland"]          = "Iceland",

                // ── Eastern Europe ───────────────────────────────────────────────
                ["transylvania"]     = "Transylvania",
                ["wallachia"]        = "Wallachia",
                ["moldavia"]         = "Moldavia",
                ["volhynia"]         = "Volhynia",
                ["masovia"]          = "Masovia",
                ["mazovia"]          = "Masovia",
                ["masuria"]          = "Masuria",
                ["mazury"]           = "Masuria",
                ["podolia"]          = "Podolia",
                ["dalmatia"]         = "Dalmatia",
                ["crimea"]           = "Crimea",
                ["ukraine"]          = "Ukraine",
                ["belarus"]          = "Belarus",
                ["siberia"]          = "Siberia",
                ["novgorod"]         = "Novgorod",
                ["moscow"]           = "Moscow Region",
                ["moscou"]           = "Moscow Region",
                ["volga"]            = "Volga Region",
                ["serbia"]           = "Serbia",
                ["croatia"]          = "Croatia",
                ["slovenia"]         = "Slovenia",
                ["bosnia"]           = "Bosnia",
                ["bulgaria"]         = "Bulgaria",
                ["romania"]          = "Romania",
                ["albania"]          = "Albania",
                ["hungary"]          = "Hungary",
                ["poland"]           = "Poland",
                ["russia"]           = "Russia",
                ["peloponnese"]      = "Peloponnese",
                ["thessaly"]         = "Thessaly",
                ["macedonia"]        = "Macedonia",
                ["thrace"]           = "Thrace",
                ["attica"]           = "Attica",
                ["greece"]           = "Greece",

                // ── Middle East & North Africa ───────────────────────────────────
                ["constantinople"]   = "Istanbul",
                ["mesopotamia"]      = "Mesopotamia",
                ["anatolia"]         = "Anatolia",
                ["istanbul"]         = "Istanbul",
                ["levant"]           = "Levant",
                ["palestine"]        = "Palestine",
                ["maghreb"]          = "Maghreb",
                ["morocco"]          = "Morocco",
                ["algeria"]          = "Algeria",
                ["tunisia"]          = "Tunisia",
                ["persia"]           = "Persia",
                ["arabia"]           = "Arabia",
                ["syria"]            = "Syria",
                ["egypt"]            = "Egypt",
                ["libya"]            = "Libya",
                ["nubia"]            = "Nubia",

                // ── Sub-Saharan Africa ───────────────────────────────────────────
                ["zululand"]         = "Zululand",
                ["transvaal"]        = "Transvaal",
                ["rhodesia"]         = "Rhodesia",
                ["abyssinia"]        = "Ethiopia",
                ["ethiopia"]         = "Ethiopia",
                ["nigeria"]          = "Nigeria",
                ["senegal"]          = "Senegal",
                ["ghana"]            = "Ghana",
                ["kenya"]            = "Kenya",
                ["sudan"]            = "Sudan",
                ["natal"]            = "Natal",
                ["congo"]            = "Congo",

                // ── South Asia ───────────────────────────────────────────────────
                ["maharashtra"]      = "Maharashtra",
                ["rajasthan"]        = "Rajasthan",
                ["karnataka"]        = "Karnataka",
                ["hyderabad"]        = "Hyderabad",
                ["calcutta"]         = "Bengal",
                ["bombay"]           = "Maharashtra",
                ["madras"]           = "Tamil Nadu",
                ["gujarat"]          = "Gujarat",
                ["mysore"]           = "Mysore",
                ["deccan"]           = "Deccan",
                ["bengal"]           = "Bengal",
                ["punjab"]           = "Punjab",
                ["sindh"]            = "Sindh",
                ["india"]            = "India",

                // ── East & Southeast Asia ────────────────────────────────────────
                ["guangdong"]        = "Guangdong",
                ["manchuria"]        = "Manchuria",
                ["indochina"]        = "Indochina",
                ["xinjiang"]         = "Xinjiang",
                ["sichuan"]          = "Sichuan",
                ["sumatra"]          = "Sumatra",
                ["hokkaido"]         = "Hokkaido",
                ["kyushu"]           = "Kyushu",
                ["yunnan"]           = "Yunnan",
                ["fujian"]           = "Fujian",
                ["canton"]           = "Guangdong",
                ["kansai"]           = "Kansai",
                ["borneo"]           = "Borneo",
                ["tibet"]            = "Tibet",
                ["annam"]            = "Annam",
                ["honshu"]           = "Honshū",
                ["siam"]             = "Siam",
                ["java"]             = "Java",
                ["kanto"]            = "Kantō",
                ["china"]            = "China",
                ["japan"]            = "Japan",

                // ── Americas: United States ──────────────────────────────────────
                ["new england"]      = "New England",
                ["massachusetts"]    = "Massachusetts",
                ["pennsylvania"]     = "Pennsylvania",
                ["connecticut"]      = "Connecticut",
                ["appalachia"]       = "Appalachia",
                ["tennessee"]        = "Tennessee",
                ["louisiana"]        = "Louisiana",
                ["mississippi"]      = "Mississippi",
                ["new jersey"]       = "New Jersey",
                ["new york"]         = "New York",
                ["kentucky"]         = "Kentucky",
                ["california"]       = "California",
                ["illinois"]         = "Illinois",
                ["missouri"]         = "Missouri",
                ["michigan"]         = "Michigan",
                ["arkansas"]         = "Arkansas",
                ["carolina"]         = "Carolina",
                ["virginia"]         = "Virginia",
                ["indiana"]          = "Indiana",
                ["alabama"]          = "Alabama",
                ["georgia"]          = "Georgia (US)",
                ["midwest"]          = "Midwest",
                ["oregon"]           = "Oregon",
                ["texas"]            = "Texas",
                ["ohio"]             = "Ohio",

                // ── Americas: Canada ─────────────────────────────────────────────
                ["british columbia"] = "British Columbia",
                ["newfoundland"]     = "Newfoundland",
                ["new brunswick"]    = "New Brunswick",
                ["nova scotia"]      = "Nova Scotia",
                ["saskatchewan"]     = "Saskatchewan",
                ["ontario"]          = "Ontario",
                ["manitoba"]         = "Manitoba",
                ["alberta"]          = "Alberta",
                ["québec"]           = "Québec",
                ["quebec"]           = "Québec",
                ["yukon"]            = "Yukon",

                // ── Americas: Latin America ──────────────────────────────────────
                ["yucatán"]          = "Yucatán",
                ["yucatan"]          = "Yucatán",
                ["venezuela"]        = "Venezuela",
                ["argentina"]        = "Argentina",
                ["colombia"]         = "Colombia",
                ["guatemala"]        = "Guatemala",
                ["ecuador"]          = "Ecuador",
                ["bolivia"]          = "Bolivia",
                ["brasil"]           = "Brazil",
                ["brazil"]           = "Brazil",
                ["chile"]            = "Chile",
                ["haiti"]            = "Haiti",
                ["cuba"]             = "Cuba",
                ["peru"]             = "Peru",
                ["mexico"]           = "Mexico",

                // ── Oceania ──────────────────────────────────────────────────────
                ["western australia"] = "Western Australia",
                ["south australia"]   = "South Australia",
                ["new south wales"]   = "New South Wales",
                ["new zealand"]       = "New Zealand",
                ["queensland"]        = "Queensland",
                ["tasmania"]          = "Tasmania",
                ["victoria"]          = "Victoria (Australia)",
                ["australia"]         = "Australia",
            };

        // ── Canonical region name → approximate centroid (lat, lng) ─────────────
        // Used for map display in API responses and PDF analytics.
        // Also used for coordinate-based proximity fallback when no keyword matches.
        public static readonly IReadOnlyDictionary<string, (double Latitude, double Longitude)> Centroids =
            new Dictionary<string, (double, double)>(StringComparer.OrdinalIgnoreCase)
            {
                // England
                ["Somerset"]            = ( 51.1051,  -2.9262),
                ["Devon"]               = ( 50.7184,  -3.5339),
                ["Dorset"]              = ( 50.7488,  -2.3445),
                ["Cornwall"]            = ( 50.2660,  -5.0527),
                ["Wiltshire"]           = ( 51.3492,  -1.9927),
                ["Hampshire"]           = ( 51.0577,  -1.3081),
                ["Surrey"]              = ( 51.2362,  -0.5704),
                ["Kent"]                = ( 51.2787,   0.5217),
                ["Sussex"]              = ( 50.9086,  -0.4822),
                ["Essex"]               = ( 51.7356,   0.4685),
                ["Greater London"]      = ( 51.5072,  -0.1276),
                ["Yorkshire"]           = ( 53.9915,  -1.5412),
                ["Lancashire"]          = ( 53.7632,  -2.7044),
                ["Derbyshire"]          = ( 53.0670,  -1.4850),
                ["Nottinghamshire"]     = ( 53.0067,  -1.0162),
                ["Lincolnshire"]        = ( 53.2308,  -0.5404),
                ["Suffolk"]             = ( 52.1872,   0.9708),
                ["Norfolk"]             = ( 52.6309,   0.8993),
                ["Cambridgeshire"]      = ( 52.2053,   0.1218),
                ["Oxfordshire"]         = ( 51.7520,  -1.2577),
                ["Gloucestershire"]     = ( 51.8642,  -2.2383),
                ["Herefordshire"]       = ( 52.0565,  -2.7158),
                ["Shropshire"]          = ( 52.7077,  -2.7416),
                ["Staffordshire"]       = ( 52.8793,  -2.0572),
                ["Cheshire"]            = ( 53.1910,  -2.5908),
                ["Cumbria"]             = ( 54.5773,  -2.7972),
                ["Northumberland"]      = ( 55.2084,  -2.0782),
                ["County Durham"]       = ( 54.7782,  -1.5740),
                ["Berkshire"]           = ( 51.4504,  -1.0907),
                ["Bedfordshire"]        = ( 52.1350,  -0.4659),
                ["Buckinghamshire"]     = ( 51.8143,  -0.8097),
                ["Hertfordshire"]       = ( 51.8098,  -0.2376),
                ["Warwickshire"]        = ( 52.2816,  -1.5870),
                ["Worcestershire"]      = ( 52.1936,  -2.2200),
                ["Leicestershire"]      = ( 52.6336,  -1.1348),
                ["Northamptonshire"]    = ( 52.2725,  -0.8756),
                ["Rutland"]             = ( 52.6555,  -0.6393),
                ["Westmorland"]         = ( 54.4315,  -2.5967),
                ["Middlesex"]           = ( 51.5080,  -0.3300),
                ["Huntingdonshire"]     = ( 52.3300,  -0.1900),

                // Scotland
                ["Scottish Highlands"]  = ( 57.1200,  -4.7100),
                ["Aberdeenshire"]       = ( 57.1497,  -2.9943),
                ["Aberdeen"]            = ( 57.1497,  -2.0943),
                ["Lothian"]             = ( 55.9533,  -3.1883),
                ["Edinburgh"]           = ( 55.9533,  -3.1883),
                ["Strathclyde"]         = ( 55.8617,  -4.2583),
                ["Glasgow"]             = ( 55.8617,  -4.2583),
                ["Argyll"]              = ( 56.2500,  -5.5000),
                ["Perthshire"]          = ( 56.4000,  -3.7500),
                ["Fife"]                = ( 56.2077,  -3.1495),
                ["Dundee"]              = ( 56.4620,  -2.9707),
                ["Inverness"]           = ( 57.4778,  -4.2247),
                ["Stirlingshire"]       = ( 56.1195,  -3.9369),
                ["Scottish Borders"]    = ( 55.5485,  -2.7861),
                ["Dumfries and Galloway"] = ( 55.0700, -3.6000),
                ["Orkney"]              = ( 59.0000,  -3.0000),
                ["Shetland"]            = ( 60.5000,  -1.2000),
                ["Caithness"]           = ( 58.4500,  -3.5500),
                ["Sutherland"]          = ( 58.0000,  -4.5000),
                ["Ayrshire"]            = ( 55.4600,  -4.6300),
                ["Renfrewshire"]        = ( 55.8400,  -4.5000),
                ["Lanarkshire"]         = ( 55.6700,  -3.8400),
                ["Angus"]               = ( 56.6500,  -2.9300),
                ["Moray"]               = ( 57.5000,  -3.2000),
                ["Scotland"]            = ( 56.4907,  -4.2026),

                // Wales
                ["Gwynedd"]             = ( 52.9243,  -4.1413),
                ["Powys"]               = ( 52.3790,  -3.5500),
                ["Ceredigion"]          = ( 52.2210,  -3.9380),
                ["Pembrokeshire"]       = ( 51.8033,  -4.9774),
                ["Carmarthenshire"]     = ( 51.8578,  -4.2100),
                ["Glamorgan"]           = ( 51.5400,  -3.3200),
                ["Monmouthshire"]       = ( 51.7600,  -2.9500),
                ["Flintshire"]          = ( 53.1700,  -3.1200),
                ["Denbighshire"]        = ( 53.0700,  -3.4200),
                ["Anglesey"]            = ( 53.2716,  -4.3500),
                ["Wrexham"]             = ( 53.0466,  -2.9937),
                ["Cardiff"]             = ( 51.4816,  -3.1791),
                ["Swansea"]             = ( 51.6214,  -3.9436),
                ["Wales"]               = ( 52.1307,  -3.7837),

                // Ireland
                ["Connacht"]            = ( 53.6930,  -8.9000),
                ["Leinster"]            = ( 53.0000,  -7.0000),
                ["Munster"]             = ( 52.0000,  -8.5000),
                ["Ulster"]              = ( 54.6000,  -6.8000),
                ["Tipperary"]           = ( 52.4740,  -8.1610),
                ["Wexford"]             = ( 52.3369,  -6.4633),
                ["Wicklow"]             = ( 52.9808,  -6.0400),
                ["Kilkenny"]            = ( 52.6541,  -7.2448),
                ["Donegal"]             = ( 54.9550,  -8.0300),
                ["Fermanagh"]           = ( 54.3480,  -7.6380),
                ["County Tyrone"]       = ( 54.5960,  -7.3000),
                ["County Antrim"]       = ( 54.9500,  -6.4700),
                ["County Armagh"]       = ( 54.3550,  -6.6600),
                ["County Londonderry"]  = ( 54.9960,  -6.8200),
                ["Sligo"]               = ( 54.2766,  -8.4761),
                ["Galway"]              = ( 53.2743,  -9.0514),
                ["Limerick"]            = ( 52.6638,  -8.6267),
                ["County Kerry"]        = ( 52.1545,  -9.5670),
                ["County Mayo"]         = ( 53.8500,  -9.5000),
                ["County Cork"]         = ( 51.8985,  -8.4756),
                ["Dublin"]              = ( 53.3498,  -6.2603),
                ["Ireland"]             = ( 53.1424,  -7.6921),

                // France
                ["Normandy"]            = ( 49.1000,   0.4000),
                ["Brittany"]            = ( 48.2020,  -2.9326),
                ["Alsace"]              = ( 48.2820,   7.4419),
                ["Burgundy"]            = ( 47.0600,   4.8580),
                ["Provence"]            = ( 43.8340,   5.8420),
                ["Languedoc"]           = ( 43.6120,   3.8770),
                ["Occitanie"]           = ( 43.6047,   1.4442),
                ["Aquitaine"]           = ( 44.8400,  -0.5800),
                ["Gascony"]             = ( 43.6500,   0.5000),
                ["Lorraine"]            = ( 48.6300,   6.2900),
                ["Champagne"]           = ( 49.0700,   4.0300),
                ["Anjou"]               = ( 47.4700,  -0.5500),
                ["Touraine"]            = ( 47.3833,   0.6833),
                ["Picardy"]             = ( 49.8941,   2.2958),
                ["Île-de-France"]       = ( 48.8566,   2.3522),
                ["Auvergne"]            = ( 45.7500,   3.0800),
                ["Poitou"]              = ( 46.5800,   0.3400),
                ["France"]              = ( 46.6034,   1.8883),

                // Germany
                ["Bavaria"]             = ( 48.7904,  11.4979),
                ["Saxony"]              = ( 51.1045,  13.2017),
                ["Thuringia"]           = ( 51.0221,  10.9040),
                ["Westphalia"]          = ( 51.7200,   7.6500),
                ["Baden-Württemberg"]   = ( 48.6616,   9.3501),
                ["Swabia"]              = ( 48.4000,   9.9000),
                ["Prussia"]             = ( 54.1000,  18.0000),
                ["Brandenburg"]         = ( 52.1100,  12.8000),
                ["Rhineland"]           = ( 50.9333,   6.9500),
                ["Hesse"]               = ( 50.6521,   9.1624),
                ["Hanover"]             = ( 52.3759,   9.7320),
                ["Pomerania"]           = ( 53.8000,  14.5000),
                ["Silesia"]             = ( 50.9000,  17.0000),
                ["Berlin"]              = ( 52.5200,  13.4050),
                ["Hamburg"]             = ( 53.5753,   9.9938),
                ["Bremen"]              = ( 53.0793,   8.8017),
                ["Germany"]             = ( 51.1657,  10.4515),

                // Austria / Switzerland
                ["Austria"]             = ( 47.5162,  14.5501),
                ["Tyrol"]               = ( 47.2700,  11.4000),
                ["Styria"]              = ( 47.3590,  14.4699),
                ["Bohemia"]             = ( 49.8175,  15.4730),
                ["Moravia"]             = ( 49.0000,  17.0000),
                ["Switzerland"]         = ( 46.8182,   8.2275),

                // Italy
                ["Tuscany"]             = ( 43.4677,  11.2453),
                ["Lombardy"]            = ( 45.4668,   9.1905),
                ["Sicily"]              = ( 37.5990,  14.0154),
                ["Sardinia"]            = ( 40.1209,   9.0129),
                ["Lazio"]               = ( 41.9027,  12.4963),
                ["Campania"]            = ( 40.8358,  14.2488),
                ["Veneto"]              = ( 45.4415,  12.3154),
                ["Piedmont"]            = ( 45.0703,   7.6869),
                ["Emilia-Romagna"]      = ( 44.4949,  11.3426),
                ["Puglia"]              = ( 40.7935,  17.1011),
                ["Calabria"]            = ( 38.9100,  16.5870),
                ["Umbria"]              = ( 43.0928,  12.4534),
                ["Liguria"]             = ( 44.4056,   8.9463),
                ["Italy"]               = ( 41.8719,  12.5674),

                // Spain
                ["Catalonia"]           = ( 41.5912,   1.5209),
                ["Andalusia"]           = ( 37.5100,  -4.0000),
                ["Aragon"]              = ( 41.6560,  -0.8773),
                ["Navarre"]             = ( 42.6955,  -1.6761),
                ["Castile"]             = ( 40.0000,  -4.0000),
                ["Valencia"]            = ( 39.4840,  -0.7533),
                ["Murcia"]              = ( 37.9922,  -1.1307),
                ["Extremadura"]         = ( 39.2765,  -6.2622),
                ["Basque Country"]      = ( 43.0000,  -2.5000),
                ["Galicia"]             = ( 42.7500,  -7.8600),
                ["Asturias"]            = ( 43.3600,  -5.8500),
                ["Cantabria"]           = ( 43.1800,  -3.9900),
                ["Madrid"]              = ( 40.4168,  -3.7038),
                ["Spain"]               = ( 40.4637,  -3.7492),

                // Portugal
                ["Algarve"]             = ( 37.0900,  -8.2300),
                ["Alentejo"]            = ( 38.0000,  -7.9000),
                ["Douro"]               = ( 41.1000,  -7.7000),
                ["Minho"]               = ( 41.7000,  -8.5000),
                ["Lisbon"]              = ( 38.7223,  -9.1393),
                ["Portugal"]            = ( 39.3999,  -8.2245),

                // Low Countries
                ["Flanders"]            = ( 51.0500,   3.7167),
                ["Wallonia"]            = ( 50.4126,   4.4447),
                ["Brabant"]             = ( 50.8700,   4.8000),
                ["Zeeland"]             = ( 51.4988,   3.6136),
                ["Gelderland"]          = ( 52.0140,   5.9900),
                ["Overijssel"]          = ( 52.4490,   6.5200),
                ["Friesland"]           = ( 53.1642,   5.7817),
                ["Holland"]             = ( 52.3700,   4.8900),
                ["Netherlands"]         = ( 52.1326,   5.2913),
                ["Belgium"]             = ( 50.5039,   4.4699),

                // Scandinavia
                ["Jutland"]             = ( 56.0000,   9.5000),
                ["Scania"]              = ( 55.8000,  13.5000),
                ["Lapland"]             = ( 68.0000,  26.0000),
                ["Dalarna"]             = ( 61.0000,  14.5000),
                ["Trøndelag"]           = ( 63.4305,  10.3951),
                ["Vestfold"]            = ( 59.2390,  10.3207),
                ["Norway"]              = ( 60.4720,   8.4689),
                ["Sweden"]              = ( 60.1282,  18.6435),
                ["Denmark"]             = ( 56.2639,   9.5018),
                ["Finland"]             = ( 61.9241,  25.7482),
                ["Iceland"]             = ( 64.9631, -19.0208),

                // Eastern Europe
                ["Transylvania"]        = ( 46.7700,  23.5800),
                ["Wallachia"]           = ( 44.5000,  26.0000),
                ["Moldavia"]            = ( 47.0000,  28.9000),
                ["Podolia"]             = ( 49.0000,  27.0000),
                ["Volhynia"]            = ( 50.7500,  25.3300),
                ["Masovia"]             = ( 52.2297,  21.0122),
                ["Masuria"]             = ( 53.8700,  21.8000),
                ["Crimea"]              = ( 45.3500,  34.1100),
                ["Poland"]              = ( 51.9194,  19.1451),
                ["Hungary"]             = ( 47.1625,  19.5033),
                ["Ukraine"]             = ( 48.3794,  31.1656),
                ["Belarus"]             = ( 53.7098,  27.9534),
                ["Russia"]              = ( 61.5240, 105.3188),
                ["Siberia"]             = ( 60.0000, 100.0000),
                ["Volga Region"]        = ( 52.0000,  47.0000),
                ["Moscow Region"]       = ( 55.7558,  37.6173),
                ["Novgorod"]            = ( 58.5244,  31.2752),
                ["Serbia"]              = ( 44.0165,  21.0059),
                ["Croatia"]             = ( 45.1000,  15.2000),
                ["Dalmatia"]            = ( 43.5100,  16.4400),
                ["Slovenia"]            = ( 46.1512,  14.9955),
                ["Bosnia"]              = ( 44.1534,  17.6783),
                ["Bulgaria"]            = ( 42.7339,  25.4858),
                ["Romania"]             = ( 45.9432,  24.9668),
                ["Albania"]             = ( 41.1533,  20.1683),
                ["Greece"]              = ( 39.0742,  21.8243),
                ["Attica"]              = ( 37.9838,  23.7275),
                ["Peloponnese"]         = ( 37.5300,  22.3700),
                ["Thessaly"]            = ( 39.5560,  22.1410),
                ["Macedonia"]           = ( 41.6086,  21.7453),
                ["Thrace"]              = ( 41.3000,  25.6000),

                // Middle East & North Africa
                ["Anatolia"]            = ( 39.0000,  35.0000),
                ["Istanbul"]            = ( 41.0082,  28.9784),
                ["Mesopotamia"]         = ( 33.0000,  44.0000),
                ["Levant"]              = ( 33.8869,  35.5131),
                ["Palestine"]           = ( 31.9474,  35.2272),
                ["Syria"]               = ( 34.8021,  38.9968),
                ["Persia"]              = ( 32.4279,  53.6880),
                ["Arabia"]              = ( 23.8859,  45.0792),
                ["Egypt"]               = ( 26.8206,  30.8025),
                ["Nubia"]               = ( 18.0000,  31.5000),
                ["Libya"]               = ( 26.3351,  17.2283),
                ["Tunisia"]             = ( 33.8869,   9.5375),
                ["Algeria"]             = ( 28.0339,   1.6596),
                ["Morocco"]             = ( 31.7917,  -7.0926),
                ["Maghreb"]             = ( 30.0000,   0.0000),

                // Sub-Saharan Africa
                ["Zululand"]            = (-28.3000,  31.4000),
                ["Transvaal"]           = (-25.7500,  28.0000),
                ["Rhodesia"]            = (-19.0154,  29.1549),
                ["Ethiopia"]            = (  9.1450,  40.4897),
                ["Kenya"]               = ( -0.0236,  37.9062),
                ["Nigeria"]             = (  9.0820,   8.6753),
                ["Ghana"]               = (  7.9465,  -1.0232),
                ["Senegal"]             = ( 14.4974, -14.4524),
                ["Sudan"]               = ( 12.8628,  30.2176),
                ["Natal"]               = (-29.0500,  30.3200),
                ["Congo"]               = ( -4.0383,  21.7587),

                // South Asia
                ["Bengal"]              = ( 23.6850,  90.3563),
                ["Punjab"]              = ( 30.9010,  75.2650),
                ["Rajasthan"]           = ( 27.0238,  74.2179),
                ["Gujarat"]             = ( 22.2587,  71.1924),
                ["Maharashtra"]         = ( 19.7515,  75.7139),
                ["Tamil Nadu"]          = ( 11.1271,  78.6569),
                ["Deccan"]              = ( 17.0000,  78.0000),
                ["Hyderabad"]           = ( 17.3850,  78.4867),
                ["Mysore"]              = ( 12.2958,  76.6394),
                ["Sindh"]               = ( 25.8900,  68.5247),
                ["Karnataka"]           = ( 15.3173,  75.7139),
                ["India"]               = ( 20.5937,  78.9629),

                // East & Southeast Asia
                ["Guangdong"]           = ( 23.1291, 113.2644),
                ["Sichuan"]             = ( 30.6547, 104.0659),
                ["Manchuria"]           = ( 43.8000, 126.0000),
                ["Tibet"]               = ( 29.6500,  91.1000),
                ["Xinjiang"]            = ( 43.7940,  87.6270),
                ["Yunnan"]              = ( 24.8800, 102.8330),
                ["Fujian"]              = ( 26.0745, 117.9895),
                ["Java"]                = ( -7.6145, 110.7121),
                ["Sumatra"]             = ( -0.5897, 101.3431),
                ["Borneo"]              = (  1.0000, 114.5000),
                ["Indochina"]           = ( 16.0000, 106.0000),
                ["Siam"]                = ( 15.8700, 100.9925),
                ["Annam"]               = ( 16.0000, 108.0000),
                ["Kantō"]               = ( 35.6895, 139.6917),
                ["Kansai"]              = ( 34.9700, 135.7490),
                ["Kyushu"]              = ( 32.7500, 131.0000),
                ["Hokkaido"]            = ( 43.7000, 142.0000),
                ["Honshū"]              = ( 37.0000, 139.0000),
                ["China"]               = ( 35.8617, 104.1954),
                ["Japan"]               = ( 36.2048, 138.2529),

                // Americas: United States
                ["New England"]         = ( 43.9500, -71.0000),
                ["Virginia"]            = ( 37.4316, -78.6569),
                ["Carolina"]            = ( 35.7595, -79.0193),
                ["Georgia (US)"]        = ( 32.1656, -82.9001),
                ["Massachusetts"]       = ( 42.4072, -71.3824),
                ["Connecticut"]         = ( 41.6032, -73.0877),
                ["Pennsylvania"]        = ( 41.2033, -77.1945),
                ["New York"]            = ( 42.1657, -74.9481),
                ["New Jersey"]          = ( 40.0583, -74.4057),
                ["Ohio"]                = ( 40.4173, -82.9071),
                ["Kentucky"]            = ( 37.8393, -84.2700),
                ["Tennessee"]           = ( 35.5175, -86.5804),
                ["Louisiana"]           = ( 30.9843, -91.9623),
                ["Mississippi"]         = ( 32.3547, -89.3985),
                ["Alabama"]             = ( 32.3617, -86.2792),
                ["Texas"]               = ( 31.9686, -99.9018),
                ["California"]          = ( 36.7783,-119.4179),
                ["Oregon"]              = ( 44.0000,-120.5000),
                ["Illinois"]            = ( 40.6331, -89.3985),
                ["Missouri"]            = ( 37.9643, -91.8318),
                ["Michigan"]            = ( 44.3148, -85.6024),
                ["Indiana"]             = ( 40.2672, -86.1349),
                ["Arkansas"]            = ( 34.7465, -92.2896),
                ["Appalachia"]          = ( 37.5000, -82.5000),
                ["Midwest"]             = ( 42.0000, -90.0000),

                // Americas: Canada
                ["Ontario"]             = ( 51.2538, -85.3232),
                ["Québec"]              = ( 52.9399, -73.5491),
                ["British Columbia"]    = ( 53.7267,-127.6476),
                ["Nova Scotia"]         = ( 44.6820, -63.7443),
                ["New Brunswick"]       = ( 46.5653, -66.4619),
                ["Newfoundland"]        = ( 53.1355, -57.6604),
                ["Manitoba"]            = ( 53.7609, -98.8139),
                ["Saskatchewan"]        = ( 52.9399,-106.4509),
                ["Alberta"]             = ( 53.9333,-116.5765),
                ["Yukon"]               = ( 64.2823,-135.0000),

                // Americas: Latin America
                ["Mexico"]              = ( 23.6345,-102.5528),
                ["Yucatán"]             = ( 20.7099, -89.0943),
                ["Peru"]                = ( -9.1900, -75.0152),
                ["Chile"]               = (-35.6751, -71.5430),
                ["Argentina"]           = (-38.4161, -63.6167),
                ["Colombia"]            = (  4.5709, -74.2973),
                ["Venezuela"]           = (  6.4238, -66.5897),
                ["Bolivia"]             = (-16.2902, -63.5887),
                ["Ecuador"]             = ( -1.8312, -78.1834),
                ["Cuba"]                = ( 21.5218, -77.7812),
                ["Haiti"]               = ( 18.9712, -72.2852),
                ["Brazil"]              = (-14.2350, -51.9253),
                ["Guatemala"]           = ( 15.7835, -90.2308),

                // Oceania
                ["New South Wales"]     = (-32.0000, 147.0000),
                ["Victoria (Australia)"]= (-36.8000, 144.9000),
                ["Queensland"]          = (-22.5750, 144.0850),
                ["South Australia"]     = (-30.0002, 136.2092),
                ["Western Australia"]   = (-27.6728, 121.6283),
                ["Tasmania"]            = (-41.4545, 145.9707),
                ["New Zealand"]         = (-40.9006, 174.8860),
                ["Australia"]           = (-25.2744, 133.7751),
            };

        /// <summary>
        /// Returns true if <paramref name="text"/> contains <paramref name="word"/> as a whole word
        /// (i.e. not preceded or followed by a letter). Case-insensitive.
        /// This prevents, for example, "kent" matching "Kentucky".
        /// </summary>
        public static bool ContainsWholeWord(string text, string word)
        {
            var idx = text.IndexOf(word, StringComparison.OrdinalIgnoreCase);
            if (idx < 0) return false;
            var startOk = idx == 0 || !char.IsLetter(text[idx - 1]);
            var endOk   = idx + word.Length >= text.Length || !char.IsLetter(text[idx + word.Length]);
            return startOk && endOk;
        }
    }
}
